name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Make gradlew executable
        run: chmod +x ./gradlew || true
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Generate/Update Gradle dependency verification metadata
        run: ./gradlew --write-verification-metadata sha256 --export-keys
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonar --info -Dsonar.automaticAnalysis=false -Dorg.gradle.jvmargs="--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED"

      - name: Definir metadados da imagem
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: felixgilioli/pedido-service

      - name: Build da imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: |
            felixgilioli/pedido-service:latest
            felixgilioli/pedido-service:v${{ github.run_number }}

  push-docker-image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push da imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            felixgilioli/pedido-service:latest
            felixgilioli/pedido-service:v${{ github.run_number }}

  deploy-kubernetes:
    runs-on: ubuntu-latest
    needs: [ push-docker-image ]
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configuração das AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Configuração do Kubectl
        run: aws eks update-kubeconfig --name tcc-eks-cluster

      - name: Instalar Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/

      - name: Processar e aplicar secrets
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
        run: |
          cd k8s
          
          if [ ! -f "secrets.yaml" ]; then
            echo "Erro: arquivo secrets.yaml não encontrado!"
            exit 1
          fi
          
          echo "Processando secrets..."
          
          envsubst < secrets.yaml > secrets_temp.yaml && mv secrets_temp.yaml secrets.yaml
          
          echo "✅ Secrets processados com sucesso!"

      - name: Deploy aplicação no Kubernetes
        env:
          IMAGE_TAG: v${{ github.run_number }}
        run: |
          cd k8s
          kustomize edit set image felixgilioli/pedido-service=felixgilioli/pedido-service:${IMAGE_TAG}
          kustomize build . | kubectl apply -f -

      - name: Verificar deployment
        run: |
          kubectl rollout status deployment/pedido-service-deployment -n tcc --timeout=300s
          kubectl get pods -n tcc